/* SPDX-License-Identifier: GPL-2.0-or-later */

#pragma once

#define VIAL_KEYBOARD_UID {0xD3, 0x73, 0x34, 0x3F, 0x58, 0xD2, 0xE0, 0x0A}
#define VIAL_UNLOCK_COMBO_COLS { 1, 1}
#define VIAL_UNLOCK_COMBO_ROWS { 0, 9}

//Vial limits
#define VIAL_COMBO_ENTRIES 64
#define VIAL_TAP_DANCE_ENTRIES 64
#define VIAL_KEY_OVERRIDE_ENTRIES 64
#define DYNAMIC_KEYMAP_LAYER_COUNT 24

#define WS2812_DI_PIN GP25
#undef RGBLED_NUM
//without LED-Strip
#define RGBLED_NUM 9
//with LED-Strip
//#define RGBLED_NUM 64

//RGBLIGHT Animations
#define RGBLIGHT_EFFECT_SNAKE
#define RGBLIGHT_EFFECT_ALTERNATING
#define RGBLIGHT_EFFECT_BREATHING
#define RGBLIGHT_EFFECT_CHRISTMAS
#define RGBLIGHT_EFFECT_KNIGHT
#define RGBLIGHT_EFFECT_RAINBOW_MOOD
#define RGBLIGHT_EFFECT_RAINBOW_SWIRL
#define RGBLIGHT_EFFECT_RGB_TEST
#define RGBLIGHT_EFFECT_SNAKE
#define RGBLIGHT_EFFECT_STATIC_GRADIENT
#define RGBLIGHT_EFFECT_TWINKLE

//RGBLIGHT Animation Settings
#define RGBLIGHT_LIMIT_VAL 240
#define RGBLIGHT_EFFECT_KNIGHT_OFFSET 9
#define RGBLIGHT_EFFECT_KNIGHT_LED_NUM 55
#define RGBLIGHT_EFFECT_KNIGHT_LENGTH 10
#define RGBLIGHT_EFFECT_SNAKE_LENGTH 10
